[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "DWScEV42ig3zGpZUhVXtuV2BzwQ4oxnFeXiBdZB6uDaZ"

[programs.devnet]
contract = "DWScEV42ig3zGpZUhVXtuV2BzwQ4oxnFeXiBdZB6uDaZ"
[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
wallet = "~/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
